version: 0.0
os: linux

#
# twe-todo-app deployment appspec.yml
#

files:
  - source: /
    destination: /var/mvcapp
hooks:
  ApplicationStop:
    - location: deployscripts/dotnetstop.sh
      runas: centos
  ApplicationStart:
    - location: deployscripts/dotnetstart.sh
      runas: centos