version: 0.2

#
# CodePipeline [ GitHub -> CodeBuilde -> CodeDeploy ] -> Lightsail
#

phases:
  install:
    commands:
      - echo dotnet --version
      - dotnet --version
      - echo copy appsettings.Production.json
      - cp ${CODEBUILD_SRC_DIR_appsettingsProduction}/appsettings.Production.json ${CODEBUILD_SRC_DIR}/twe-todo-app/
  pre_build:
    commands:
      - echo build clean start
      - dotnet clean -c Release
      - echo build clean complete
  build:
    commands:
      - echo build start
      - dotnet build -c Release
      - echo build completed
  post_build:
    commands:
      - echo publish start
      - dotnet publish -c Release
      - echo publish complete
      - echo copy scripts dir
      - cp -r deployscripts twe-todo-app/bin/Release/netcoreapp2.2/publish/
      - echo copy appspec.yml
      - cp appspec.yml twe-todo-app/bin/Release/netcoreapp2.2/publish/
artifacts:
  files:
    - '**/*'
  base-directory: 'twe-todo-app/bin/Release/netcoreapp2.2/publish'